config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "projects#index"
  resources :events
  resources :projects

  get "/projects/:id/start_clock", to: 'projects#start_clock', as: :start_clock
  get "/projects/:id/stop_clock", to: 'projects#stop_clock', as: :stop_clock
  get "/projects/:id/events", to: 'projects#events', as: :project_events
  get "/heartbeat_mouse", to: "heartbeats#heartbeat_mouse", as: :heartbeat_mouse

  get "/heartbeats", to: "heartbeats#index", as: :heartbeats
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :project

  before_save :update_seconds

  def duration
    if is_running?
      "#{current_duration_in_minutes} minutes and counting"
    else
      "#{current_duration_in_minutes} minutes"
    end
  end

  def formatted_time
    start_time.localtime.strftime("%b %e, %l:%M %p")
  end

  def time_and_duration
    "#{duration}: #{formatted_time}"
  end

  def is_running?
    end_time.nil?
  end

  private

  def current_duration_in_minutes
    final = is_running? ? Time.now : end_time
    seconds = (final - start_time)
    (seconds/60).to_i
  end

  private

  def update_seconds
    return if end_time.nil?
    self.seconds = end_time - start_time
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:project_id, :start_time, :end_time)
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def duration_in_hours(minutes)
    if minutes
      "%.2f" % (minutes/60.0)
    else
      "Zero"
    end
  end

  def formatted_duration(event)
    if event.seconds
      "#{formatted_time(event.start_time)} - #{formatted_time(event.end_time)} ... %d minutes" % [event.seconds/60]
    else
      seconds = Time.now - event.start_time
      "#{formatted_time(event.start_time)} - now ... %d minutes" % (seconds / 60)
    end
  end

  def formatted_duration_event(event)
    if event.seconds
      "%.2f hours" % (event.seconds/3600.0)
    else
      seconds = Time.now - event.start_time
      "%.2f - running" % (seconds / 3600.0)
    end
  end

  def formatted_time(time)
    time.strftime("%I:%M")
  end
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.number_field :project_id %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.project_id %></td>
        <td><%= event.start_time %></td>
        <td><%= event.end_time %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<% if @event.end_time.nil? %>
  <p>
  Started clock at: <%= @event.formatted_time %>
  </p>

  <div class='stop-clock-link'>
    <%= link_to 'Stop Clock', stop_clock_path(@event.project_id) %>
  </div>

<% else %>
  <p>
  <%= @event.time_and_duration %>
  </p>

<% end %>

<%= link_to "Back to #{@event.project.name}", project_path(@event.project) %>