config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "projects#index"
  resources :events
  resources :projects

  get "/projects/:id/start_clock", to: 'projects#start_clock', as: :start_clock
  get "/projects/:id/stop_clock", to: 'projects#stop_clock', as: :stop_clock
  get "/projects/:id/events", to: 'projects#events', as: :project_events
  get "/heartbeat_mouse", to: "heartbeats#heartbeat_mouse", as: :heartbeat_mouse

  get "/heartbeats", to: "heartbeats#index", as: :heartbeats
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :events

  def current_weeks_events
    # events.select { |event| event.start_time > Date.today.at_beginning_of_week}
    events
  end

  def event_summaries
    summaries = {}
    events.each do |event|
      next if event.end_time.nil?
      next if event.seconds.nil?
      date_string = event.start_time.strftime("%Y-%m-%d")
      if summaries[date_string]
        summaries[date_string] += event.seconds/60.0
      else
        summaries[date_string] = event.seconds/60.0
      end
    end
    summaries = summaries.keys.sort { |date1, date2| date2 <=> date1 }.map do |date|
      OpenStruct.new(date: date, total_minutes: summaries[date])
    end
    summaries
  end

  def recent_events
    events.where("start_time > ? ", 3.weeks.ago).order("start_time desc")
  end

  def start_clock
    events.create start_time: Time.now
  end

  def stop_clock
    event = events.last
    return if event.end_time
    event.update_attributes(end_time: Time.now)
  end

  def is_running?
    return false if events.empty?
    events.last.is_running?
  end

  def self.active_project
    event = Event.last
    return nil if event.nil?
    if event.is_running?
      event.project
    else
      nil
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :start_clock, :stop_clock]
  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @event_summaries = @project.event_summaries
    @recent_events = @project.recent_events
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def stop_clock
    @project.stop_clock
    redirect_to project_url(@project)
  end

  def start_clock
    @project = Project.find(params[:id])
    @project.start_clock
    redirect_to project_url(@project)
  end

  def events
    @project = Project.find(params[:id])
    render json: @project.current_weeks_events
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def event_row_class(event)
    if event.is_running?
      "project-event running"
    else
      "project-event not-running"
    end
  end
end

app/views/projects/_event_details.html.erb
<% # console %>

<div class='event-summary'>
  <div class='event-summary-row'>
    <div class="event-summary-head">
      <%= summary.date %>: <%= duration_in_hours(summary.total_minutes) %> hours
    </div>
    <div class='event-summary-details'>
      <% @recent_events.each do |event| %>
        <% if event.start_time.strftime('%Y-%m-%d') == summary.date %>
          <div class="<%= event_row_class(event) %>" >
            <% if event.is_running? %>
              <%= formatted_duration(event) %>
            <% else %>
              <%= link_to formatted_duration(event), edit_event_path(event) %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<% if active_project = Project.active_project %>
  <div class='stop-clock'>
    <%= link_to "Stop the clock", stop_clock_path(id: active_project.id), class: "toggle-clock" %>
  </div>
<% end %>

<table>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<% content_for :nav do %>
    | <%= link_to @project.name, edit_project_path(@project) %>
<% end %>

<div class='project'>

  <% if @project.is_running? %>
    <div class='stop-clock'>
      <%= link_to "Stop the clock", stop_clock_path(id: @project.id), class: "toggle-clock" %>
    </div>
  <% else %>
    <% unless Project.active_project %>
      <div class='start-clock'>
        <%= link_to "Start the clock", start_clock_path(id: @project.id), class: "toggle-clock" %>
      </div>
    <% end %>
  <% end %>

  <div class='project-events'>
    <% @project.event_summaries.each do |summary| %>
      <%= render partial: "event_details", locals: {summary: summary} %>
    <% end %>
  </div>

<div>

</div>

</div>